db_dir: /home/pmancini/Code/generate_mtb_reports/data/
protocol: MULTIPLI
catalog: gvx_samples_catalog.sqlite # Catalog database file


redcap_api_url: 'http://(ip)/redcap/api/'

# eCRF
crf_host: 'ftps2.isped.u-bordeaux2.fr'
path_crf_file: 'MULTIPLI/IMPORT/Multipli_samples_mtb_test.csv'

local_MTB_file: 'data/Multipli_samples_mtb_test.csv'

# Script dependency:
# - update_redcap_record.py
path_to_utils: '../cron_to_redcap/'

path_to_logs: .

path_to_data: data/

template: template_pre_mtb/Template_pre_MTB.tex