db_dir: /home/pmancini/Code/generate_mtb_reports/data/
protocol: MULTIPLI
catalog: gvx_samples_catalog.sqlite # Catalog database file


redcap_api_url: 'http://129.10.20.120/redcap/api/'

# eCRF
crf_host: 'ftps2.isped.u-bordeaux2.fr'


# Script dependency:
# - update_redcap_record.py
path_to_utils: /home/pmancini/Code/Redcap_utils/

template: template_pre_mtb/Template_pre_MTB.tex